name: Deploy Production

on:
  # Trigger the workflow on push or pull request,
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # This workflow contains a single job called "deploy"/.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: echo "${{secrets.ENV_PRODUCTION}}" > .env
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build --platform linux/amd64 -t 090920019999/client:v0 .
      - name: Push Docker image
        run: docker push 090920019999/client:v0
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          key: ${{ secrets.SSH_KEY_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin
            docker pull 090920019999/client:v0
            docker stop client
            docker rm client
            docker run -dp 3000:3000 --name client 090920019999/client:v0
